### Get all books
GET http://localhost:8080/v1/books
Accept: application/json

### Get book by ISBN
GET http://localhost:8080/v1/books/978-1234567890
Accept: application/json

### Variables
@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}

### Get all books (using variables)
GET {{baseUrl}}/v1/books
Accept: application/json

### Get book by ISBN (using variables)
GET {{baseUrl}}/v1/books/978-1234567890
Accept: application/json
